### ISSUE TITLE
Enable only mapping of IDs

### ISSUE THREAD

**Issue by sulheim** [lobolab/mergem#1]
Hey, this looks great! 
The mapping you do here seems very thorough, but would it be possible to map the namespace of one model to a different namespace without actually merging models?

**Comment by dnlobo** [comment]
Thanks. That's a great idea. We'll implement it in a future release.

**Comment by PratikPathade** [comment]
hey, I am using mergem for merging two models. i am giving the input file in mat format but some fields are absent in the output format which is also in mat format. I need all the fields which are there in my input file. what can I do?

**Comment by dnlobo** [comment]
A merged model only contains reactions, metabolites, and objective functions. If needed, you could copy back any other field to the merged model after it has been created with the tool. Please let us know if you are missing anything in particular that you could not copy back.

**Comment by dnlobo** [comment]
@sulheim, this functionality is now implemented. To translate models, you  can use the new function (translate) we have added to the mergem package, an option in the command line (-t), and you can also translate models in [Fluxer](https://fluxer.umbc.edu/). Hopefully this is useful.
