### ISSUE TITLE
cobra version

### ISSUE THREAD

**Issue by hariszaf** [lobolab/mergem#4]
Hi there and thanks for the great resource!

It is my belief that you need to change in your [`requirements.txt`](https://github.com/lobolab/mergem/blob/e149638982f3cf668826dae0a444cfb944c028c5/requirements.txt#L2) the `cobra` version.

You are using the `cobra.core.Gene.GPR` class and I think it was first introduced in [`cobra==0.24.0`](https://github.com/opencobra/cobrapy/releases/tag/0.24.0).

Here is the [initial commit](https://github.com/opencobra/cobrapy/commit/01d60ecba13da4c7cc6780304b902f141d6b96a6) of the class.

**Comment by dnlobo** [comment]
Hi, I'm glad you are finding it useful. Thank you for the tip. I have updated the requirements in the last commit as suggested.
