### ISSUE TITLE
Possibility of Parelarization 

### ISSUE THREAD

**Issue by ggmirandac** [lobolab/mergem#5]
Hi,

I am using you software to combine different models into one big meta-metabolic network. And I am wondering if there is a way to paralelize the process specially in the bottle neck that is the generation of the models (For example when they are stored in a SBML file). Then once created they merge them all.

Bests,

Gabriel

**Comment by dnlobo** [comment]
Hi Gabriel,

I've never tried, but I think you could load all the models in parallel using the multiprocessing package in Python, and after that call the merge function. See the first example here: 

https://docs.python.org/3/library/multiprocessing.html

Good luck!
